---
devices:
  samplerate: 44100
  chunksize: 4096
  capture:
    type: RawFile
    filename: "dummy"
    channels: 2
    format: S16LE
  playback:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE

filters:
  atten:
    type: Gain
    parameters:
      gain: -12
      inverted: false
  quantize:
    type: Dither
    parameters:
      type: None
      bits: 8
  dithereven:
    type: Dither
    parameters:
      type: Flat
      bits: 8
      amplitude: 1.0
  dithersimple:
    type: Dither
    parameters:
      type: Highpass
      bits: 8
  ditherfancy:
    type: Dither
    parameters:
      type: Lipshitz441
      bits: 8
  ditherfancy2:
    type: Dither
    parameters:
      type: Fweighted441
      bits: 8
  ditherfancy3:
    type: Dither
    parameters:
      type: Shibata441
      bits: 8

pipeline:
  - type: Filter
    channels: [0, 1]
    names:
      - atten
      - ditherfancy2


