---
devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE
  playback:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE

filters:
  lowpass_fir:
    type: Conv
    parameters:
      type: Raw 
      filename: filter.txt

pipeline:
  - type: Filter
    channels: [0, 1]
    names:
      - lowpass_fir
   

