---
devices:
  samplerate: 48000
  chunksize: 1024
  resampler: 
    type: AsyncSinc
    profile: Balanced
  capture_samplerate: 44100
  capture:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE
  playback:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE

   

