---
devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE
  playback:
    type: File
    filename: "dummy"
    channels: 2
    format: S16LE

filters:
  filter44100:
    type: Biquad
    parameters:
      type: Highpass
      freq: 80
      q: 0.5
  filter48000:
    type: Biquad
    parameters:
      type: Highpass
      freq: 100
      q: 0.5
  demofilter:
    type: Conv
    parameters:
      type: Raw
      filename: filter_$samplerate$_$channels$.txt

pipeline:
  - type: Filter
    channel: 0
    names:
      - demofilter
      - filter$samplerate$
  - type: Filter
    channel: 1
    names:
      - demofilter
   

