on: [push, pull_request]

name: CI test and lint

jobs:
  check_test_arm64:
    name: Check and test Linux arm 64bit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build image
        run: docker build -t cross/armv8:v1 --file Dockerfile_armv8 ./

      - name: Run cargo check
        run: cross check --target aarch64-unknown-linux-gnu

      - name: Run cargo test for arm
        run: cross test --target aarch64-unknown-linux-gnu

  check_macos_arm:
    name: Check and test macOS Arm
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        run: cargo check --no-default-features

      - name: Run cargo test
        run: cargo test --no-default-features
