name: Publish

on:
  push:
  release:
    types:
      - created

jobs:
  linux_amd64:
    name: Linux amd64
    runs-on: ubuntu-latest
    #container: ubuntu:20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Update package list
        run: sudo apt-get update

      - name: Install utils
        run: sudo apt-get install curl wget -y

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Alsa devel
        run: sudo apt-get install libasound2-dev -y

      - name: Install OpenSSL
        run: sudo apt-get install openssl libssl-dev -y

      - name: Build with Alsa only
        run: cargo build --release

      - name: Compress
        run: tar -zcvf camilladsp.tar.gz -C target/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-amd64
          path: camilladsp.tar.gz
          retention-days: 14

      - name: Upload binary to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.tar.gz
          asset_name: camilladsp-linux-amd64.tar.gz
          tag: ${{ github.event.release.tag_name }}

      - name: Install PipeWire development files
        run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install libpipewire-0.3-dev -y

      - name: Build with PipeWire
        run: cargo build --release --features pipewire-backend

      - name: Compress binary with PipeWire
        run: tar -zcvf camilladsp-pipewire.tar.gz -C target/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary with PipeWire artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-pipewire-amd64
          path: camilladsp-pipewire.tar.gz
          retention-days: 14

      - name: Upload binary with PipeWire to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp-pipewire.tar.gz
          asset_name: camilladsp-linux-pipewire-amd64.tar.gz
          tag: ${{ github.event.release.tag_name }}

      - name: Install PulseAudio development files
        run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install libpulse0 libpulse-dev -y

      - name: Build with PulseAudio
        run: cargo build --release --features pulse-backend

      - name: Compress binary with PulseAudio
        run: tar -zcvf camilladsp-pulse.tar.gz -C target/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary with PulseAudio artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-pulseaudio-amd64
          path: camilladsp-pulse.tar.gz
          retention-days: 14

      - name: Upload binary with PulseAudio to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp-pulse.tar.gz
          asset_name: camilladsp-linux-pulseaudio-amd64.tar.gz
          tag: ${{ github.event.release.tag_name }}

  linux_aarch64:
    name: Linux aarch64
    runs-on: ubuntu-24.04-arm
    #container: ubuntu:20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Update package list
        run: sudo apt-get update

      - name: Install utils
        run: sudo apt-get install curl wget -y

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Alsa devel
        run: sudo apt-get install libasound2-dev -y

      - name: Install OpenSSL
        run: sudo apt-get install openssl libssl-dev -y

      - name: Build with Alsa only
        run: cargo build --release

      - name: Compress
        run: tar -zcvf camilladsp.tar.gz -C target/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-aarch64
          path: camilladsp.tar.gz
          retention-days: 14

      - name: Upload binary to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.tar.gz
          asset_name: camilladsp-linux-aarch64.tar.gz
          tag: ${{ github.event.release.tag_name }}

      - name: Install PipeWire development files
        run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install libpipewire-0.3-dev -y

      - name: Build with PipeWire
        run: cargo build --release --features pipewire-backend

      - name: Compress binary with PipeWire
        run: tar -zcvf camilladsp-pipewire.tar.gz -C target/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary with PipeWire artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-pipewire-aarch64
          path: camilladsp-pipewire.tar.gz
          retention-days: 14

      - name: Upload binary with PipeWire to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp-pipewire.tar.gz
          asset_name: camilladsp-linux-pipewire-aarch64.tar.gz
          tag: ${{ github.event.release.tag_name }}

      - name: Install PulseAudio development files
        run: DEBIAN_FRONTEND="noninteractive" sudo apt-get install libpulse0 libpulse-dev -y

      - name: Build with PulseAudio
        run: cargo build --release --features pulse-backend

      - name: Compress binary with PulseAudio
        run: tar -zcvf camilladsp-pulse.tar.gz -C target/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary with PulseAudio artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-pulseaudio-aarch64
          path: camilladsp-pulse.tar.gz
          retention-days: 14

      - name: Upload binary with PulseAudio to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp-pulse.tar.gz
          asset_name: camilladsp-linux-pulseaudio-aarch64.tar.gz
          tag: ${{ github.event.release.tag_name }}

  linux_armv7:
    name: Linux armv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-unknown-linux-gnueabihf

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build image
        run: docker build -t cross/armv7:v1 --file Dockerfile_armv7 ./

      - name: Build
        run: cross build --release --target armv7-unknown-linux-gnueabihf
        env:
          RUSTFLAGS: "-C target-feature=+neon"

      - name: Compress binary
        run: tar -zcvf camilladsp.tar.gz -C target/armv7-unknown-linux-gnueabihf/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-armv7
          path: camilladsp.tar.gz
          retention-days: 14

      - name: Upload binary to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.tar.gz
          asset_name: camilladsp-linux-armv7.tar.gz
          tag: ${{ github.event.release.tag_name }}

  linux_armv6:
    name: Linux armv6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: arm-unknown-linux-gnueabihf

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build image
        run: docker build -t cross/armv6:v1 --file Dockerfile_armv6 ./

      - name: Build
        run: cross build --release --target arm-unknown-linux-gnueabihf

      - name: Compress
        run: tar -zcvf camilladsp.tar.gz -C target/arm-unknown-linux-gnueabihf/release camilladsp --owner=0 --group=0 --numeric-owner

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-linux-armv6
          path: camilladsp.tar.gz
          retention-days: 14

      - name: Upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.tar.gz
          asset_name: camilladsp-linux-armv6.tar.gz
          tag: ${{ github.event.release.tag_name }}

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Compress
        run: powershell Compress-Archive target/release/camilladsp.exe camilladsp.zip

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-windows-amd64
          path: camilladsp.zip
          retention-days: 14

      - name: Upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.zip
          asset_name: camilladsp-windows-amd64.zip
          tag: ${{ github.event.release.tag_name }}

      - name: Build with ASIO backend
        run: cargo build --release --features asio-backend

      - name: Compress with ASIO backend
        run: powershell Compress-Archive target/release/camilladsp.exe camilladsp-asio.zip

      - name: Upload binary artifact with ASIO backend
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-windows-asio-amd64
          path: camilladsp-asio.zip
          retention-days: 14

      - name: Upload binary with ASIO backend to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp-asio.zip
          asset_name: camilladsp-windows-asio-amd64.zip
          tag: ${{ github.event.release.tag_name }}

  macos:
    name: macOS Intel
    runs-on: macos-15-intel
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Compress
        run: tar -zcvf camilladsp.tar.gz -C target/release camilladsp

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-macos-amd64
          path: camilladsp.tar.gz
          retention-days: 14

      - name: Upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.tar.gz
          asset_name: camilladsp-macos-amd64.tar.gz
          tag: ${{ github.event.release.tag_name }}


  macos_arm:
    name: macOS Arm
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Compress
        run: tar -zcvf camilladsp.tar.gz -C target/release camilladsp

      - name: Upload binary artifact
        uses: actions/upload-artifact@v6
        with:
          name: camilladsp-macos-aarch64
          path: camilladsp.tar.gz
          retention-days: 14

      - name: Upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: camilladsp.tar.gz
          asset_name: camilladsp-macos-aarch64.tar.gz
          tag: ${{ github.event.release.tag_name }}

  publish_crate:
    name: Publish to crates.io
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [linux_amd64, linux_aarch64, linux_armv7, linux_armv6, windows, macos, macos_arm]
    runs-on: ubuntu-latest
    steps:
      - name: Check tag is a plain release version
        run: echo "${{ github.event.release.tag_name }}" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}